### PR TITLE
Add debug feature

### PR DESCRIPTION
**Pull request by yihaozhadan**
1. Add [debug](https://www.npmjs.com/package/debug) feature. So that it is able to trace response status,  next retry delay, current retry attempt in console.
2. Upgrade mocha version to resolve vulnerabilities.
3. Add .gitignore file.

### CODE REVIEW

**Comment by yihaozhadan** [comment]
@stephenplusplus 
I upgrade the Mocha version. It seems that *circleci* doesn't allow [Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) syntax. Can you help?

**Comment by kolodny** [comment]
I would suggest removing node v4 since that's past it's EOL and add nodev10 to the mix. You can find that config in https://github.com/stephenplusplus/retry-request/blob/master/.circleci/config.yml

**Comment by yihaozhadan** [comment]
@stephenplusplus Can you update CircleCI settings?

**Comment by yihaozhadan** [comment]
@stephenplusplus I updated [config.yml](https://github.com/stephenplusplus/retry-request/blob/master/.circleci/config.yml) file and it seems good now.

**Comment by stephenplusplus** [comment]
Thank you @yihaozhadan! I followed your advice and updated the CI configuration to accept newer versions of Node (#26), and then made some lint-y modifications to your changes in this PR. A merge and release will follow. Thanks again!

**Comment by stephenplusplus** [comment]
And just a note about why I removed the gitignore file for `node_modules`. I used to have this in my repos, then someone told me about the global gitignore file (https://help.github.com/en/articles/ignoring-files). I have since been using that to define the basics:

```
node_modules
.DS_Store
*.log
__* // <-- this one is a bit risky, but it's my own way to leave sensitive files inside of repos I'm working on without worrying about adding them. E.g. key files
```

**Pull request merged**
